name: Unit test

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Run unit tests"
        type: boolean
        default: true
        required: false

  pull_request:
    branches: [ "main", "dev" ]

defaults:
  run:
    working-directory: ./

env:
  NODE_VERSION: 18.x
  unit-tests: ${{ github.event.inputs.js || true }}

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
    
  unit-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v3
        id: restore-node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.restore-node_modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Performing unit tests
        run: npm test

  
