name: Unit test

on:
  workflow_dispatch:
    inputs:
      sol:
        description: "Test using solidity unit tests"
        type: boolean
        default: false
        required: false
      js:
        description: "Test using js unit tests"
        type: boolean
        default: true
        required: false

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - run: npm ci
    - name: Performing unit tests using the solidity testing environment
      if: ${{ inputs.sol == true }} || env.sol == true
      run: npm run test-sol
    - name: Performing unit tests using the js testing environment
      if: ${{ inputs.js == true }} || env.js == true
      run: npm run test-js

  
